### PR TITLE
Update

### PR DESCRIPTION
**Pull request by diasdavid**
Finding some issues while updating the deps:

- [x] fix missing code in js-multihash
- [x] update test to not assume that we implement all the hash functions
- [ ] Figure out why there are tests still failing

### CODE REVIEW

**Comment by diasdavid** [comment]
@beanow I followed https://github.com/ipfs/js-ipfs-unixfs-engine/issues/187#issuecomment-336617606 and started updating the deps.

I'm being unsuccessful getting unixfs-engine tests to pass with pull-block 1.2.1. With 1.2.0 they pass just fine. Did you have the chance to try running them in your machine?

**Comment by Beanow** [comment]
@diasdavid nice find. It's looking like a performance regression for a test-case that I hadn't considered in previous tests. I was able to reproduce and quantify this with the other benchmarking tools I've set up.

Test|Version|Min|AVG|Max
-|-|-:|-:|-:
perByteSmall|v1.2.1|12ms|14ms|37ms
perByteSmall|v1.2.0|3ms|4ms|10ms
perByteMedium|v1.2.1|230ms|246ms|476ms
perByteMedium|v1.2.0|42ms|44ms|47ms

Essentially in `test/test-fixed-size-chunker.js`
The testing method used is

```
pull(
  pull.values(rawFile),
  chunker(KiB256),
  //...
)
```

This usage of `pull.values(rawFile)` feeds the chunker _one byte at a time_ as opposed to more sizable buffers. This will cause it to do 262144 receptions of a single byte buffer and 262144 merges of those buffers per block. Which contains more logic in the later version.

I'll have a look at this scenario and you can look forward to pull-block 1.2.2 soon :nerd_face:

Note that the tests fail due to an 80 second timeout. So the output is still correct, just very slow with these particular tests. I'll let you decide if you want to tweak parameters and release 1.2.1 or wait for a fix.

**Comment by dignifiedquire** [comment]
we should check and make sure we don’t do this anywhere in the actual code, as that would mean a large inefficency even when we optimize pull-block more

**Comment by diasdavid** [comment]
I'm locking pull-block to 1.2.0 to unblock other updates. Once pull-block 1.2.2 is finished, I'll updated it right away :)

**Pull request merged**
